import './globals.css';
import type { Metadata } from 'next';
import { Aclonica, Inter, Montserrat } from 'next/font/google';
import Navbar from './components/Navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

const aclonica = Aclonica({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-aclonica',
});
const montserrat = Montserrat({
  subsets: ['latin'],
  weight: '600',
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: 'Hearthstone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` ${aclonica.className} bg-navbarColor bg-homepageBackground bg-cover min-h-screen`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
